basePath: /api/v1
definitions:
  handler.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role:
        enum:
        - admin
        - user
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - password
    - role
    - username
    type: object
  handler.DeleteAPIKeyRequest:
    properties:
      api_key_id:
        type: integer
    required:
    - api_key_id
    type: object
  handler.DeleteUserRequest:
    properties:
      user_id:
        minimum: 1
        type: integer
    required:
    - user_id
    type: object
  handler.GenerateAPIKeyRequest:
    properties:
      description:
        type: string
      expires_at:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  handler.ResetPasswordRequest:
    properties:
      new_password:
        minLength: 6
        type: string
      user_id:
        minimum: 1
        type: integer
    required:
    - new_password
    - user_id
    type: object
  handler.UpdateUserRequest:
    properties:
      email:
        type: string
      role:
        enum:
        - admin
        - user
        type: string
      status:
        enum:
        - 0
        - 1
        type: integer
    type: object
  model.APIKey:
    properties:
      api_key:
        type: string
      created_at:
        type: string
      expires_at:
        type: string
      id:
        type: integer
      key_name:
        type: string
      status:
        description: '0: disabled, 1: active'
        type: integer
      user_id:
        type: integer
    type: object
  model.APIResponse:
    description: 统一API响应格式
    properties:
      code:
        description: 状态码，0表示成功
        example: 0
        type: integer
      data:
        description: 响应数据
      message:
        description: 状态信息
        example: ok
        type: string
    type: object
  model.ChangePasswordRequest:
    properties:
      current_password:
        minLength: 6
        type: string
      new_password:
        minLength: 6
        type: string
    required:
    - current_password
    - new_password
    type: object
  model.ChangePasswordResponse:
    properties:
      message:
        type: string
    type: object
  model.LoginRequest:
    properties:
      password:
        maxLength: 100
        minLength: 6
        type: string
      username:
        maxLength: 50
        minLength: 1
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResponse:
    properties:
      access_token:
        type: string
      expires_in:
        description: 访问令牌过期时间(秒)
        type: integer
      token_type:
        type: string
      user:
        $ref: '#/definitions/model.UserInfo'
    type: object
  model.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  model.UpdateProfileRequest:
    properties:
      email:
        type: string
    type: object
  model.UpdateProfileResponse:
    properties:
      message:
        type: string
      user:
        $ref: '#/definitions/model.UserInfo'
    type: object
  model.UserInfo:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      role:
        type: string
      status:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  model.UserListResponse:
    properties:
      total:
        type: integer
      users:
        items:
          $ref: '#/definitions/model.UserInfo'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 统一API业务服务框架，实现多种功能性服务API并集中管理
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: APIHub API
  version: "1.0"
paths:
  /api/v1/dashboard/user/create:
    post:
      consumes:
      - application/json
      description: 创建新的系统用户
      parameters:
      - description: 创建用户请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserInfo'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 创建新用户
      tags:
      - 用户管理
  /api/v1/dashboard/user/delete:
    post:
      consumes:
      - application/json
      description: 删除指定的用户
      parameters:
      - description: 删除用户请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.DeleteUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 删除用户
      tags:
      - 用户管理
  /api/v1/dashboard/user/info/{id}:
    get:
      consumes:
      - application/json
      description: 根据用户ID获取用户详细信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserInfo'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 获取用户信息
      tags:
      - 用户管理
  /api/v1/dashboard/user/list:
    get:
      consumes:
      - application/json
      description: 分页获取系统中的用户列表
      parameters:
      - description: 页码，默认1
        in: query
        minimum: 1
        name: page
        type: integer
      - description: 每页数量，默认20
        in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserListResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 获取用户列表
      tags:
      - 用户管理
  /api/v1/dashboard/user/reset-password:
    post:
      consumes:
      - application/json
      description: 重置指定用户的密码
      parameters:
      - description: 重置密码请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 重置用户密码
      tags:
      - 用户管理
  /api/v1/dashboard/user/update/{id}:
    post:
      consumes:
      - application/json
      description: 更新指定用户的信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新用户请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserInfo'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 更新用户信息
      tags:
      - 用户管理
  /auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录获取JWT Token
      parameters:
      - description: 登录请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
      summary: 用户登录
      tags:
      - 认证
  /auth/logout:
    post:
      consumes:
      - application/json
      description: 用户登出，撤销JWT Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LogoutResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 用户登出
      tags:
      - 认证
  /auth/password/change:
    post:
      consumes:
      - application/json
      description: 修改当前登录用户的密码
      parameters:
      - description: 修改密码请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ChangePasswordResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 修改密码
      tags:
      - 认证
  /auth/profile:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserInfo'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 获取当前用户信息
      tags:
      - 认证
  /auth/profile/update:
    post:
      consumes:
      - application/json
      description: 更新当前登录用户的个人资料
      parameters:
      - description: 更新个人资料请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UpdateProfileResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 更新个人资料
      tags:
      - 认证
  /dashboard/apikeys/delete:
    post:
      consumes:
      - application/json
      description: 删除当前用户的指定API密钥
      parameters:
      - description: API密钥删除请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.DeleteAPIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 删除API密钥
      tags:
      - API密钥
  /dashboard/apikeys/generate:
    post:
      consumes:
      - application/json
      description: 为当前用户生成新的API密钥
      parameters:
      - description: API密钥生成请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.GenerateAPIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.APIKey'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 生成API密钥
      tags:
      - API密钥
  /dashboard/apikeys/list:
    get:
      consumes:
      - application/json
      description: 列出当前用户的所有API密钥
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.APIKey'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      security:
      - BearerAuth: []
      summary: 列出API密钥
      tags:
      - API密钥
  /health:
    get:
      description: 返回服务健康状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
      summary: 健康检查接口
      tags:
      - 系统
securityDefinitions:
  ApiKeyAuth:
    description: API Key 认证
    in: header
    name: X-API-Key
    type: apiKey
  BearerAuth:
    description: 请输入 "Bearer {token}" 格式的JWT令牌
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
